/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: tranminhluan (https://sketchfab.com/tranminhluan) // added proper credit to the creator whose model i have used
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-16-pro-96be8c7e49fa4f949855db3e7f2e64e0
Title: Iphone 16 Pro
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";

function Model(props) {
  const { nodes, materials } = useGLTF("/models/scene.glb");

  const texture = useTexture(props.item.img);
  //four color, black ,white,natural,desert

  // using the color to adjust the material color as model is not desinged for evryh color and until low sized mode, is made we cant add as addikng multiple mode will make the site more heavier 
  useEffect(() => {
    Object.entries(materials).map((material) => {
      if (

        // used different material color code so that we could map them over hte model 
        
        material[0] !== "zFdeDaGNRwzccye" &&
        material[0] !== "ujsvqBWRMnqdwPx" &&
        material[0] !== "hUlRcbieVuIiOXG" &&
        material[0] !== "jlzuBkUzuJqgiAK" &&
        material[0] !== "xNrofRCqOXXHVZt"
      ) {
        material[1].color = new THREE.Color(props.item.color[0]);
      }
      material[1].needsUpdate = true;
    });
  }, [materials, props.item]);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.phone16pro}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9.geometry}
        material={materials.phone16pro}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.phone16pro_transparent}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_15.geometry}
        material={materials.phone16pro}
      />
    </group>
  );
}
export default Model;

useGLTF.preload("/models/scene.glb");